### ISSUE TITLE
check exist in cache

### ISSUE THREAD

**Issue by pishguy** [eGust/flutter_cache_store#3]
you suppose we cache file from `url`

```dart
  File file = await store.getFile(
    'url', // GET method
    key: null, // use custom string instead of URL
    headers: {}, // same as http.get
    fetch: myFetch, // Optional: CustomFunction for making custom request
    // Optional: Map<String, dynamic> any custom you want to pass to your custom fetch function.
    custom: {'method': 'POST', 'body': 'test'},
    flushCache: false, // whether to re-download the file
  );
```

now how can i check exist cached file from `url` and make request if it doesn't in cache or if its exiting in cache, i can do something with that

**Comment by eGust** [comment]
That's not how caching should work. You should always ask the store for a file. Because of your action matters to the policy. 

Another problem is, what if you async check it, and later the file just had expired and deleted when you want to use it?

You probably need to implement a custom policy to do your logic.
