### ISSUE TITLE
Possibility to instantiate multiple instances of CacheStore

### ISSUE THREAD

**Issue by MallorcaSoftware** [eGust/flutter_cache_store#5]
Would be great if we have a possibility to create multiple instances of cache store with for example different cache policies or different httpGetters.

**Comment by eGust** [comment]
Hi @MallorcaSoftware 
In the beginning, I had the same idea. But later I changed my mind because:
1. All files are cached under the same folder. 2 stores are generating the same file name would cause problems
2. If using different namespaces for multiple stores, the same file could be cached multiple times

Maybe I can add more params to `getInstance` to support a namespace and a policy?

**Comment by MallorcaSoftware** [comment]
> If using different namespaces for multiple stores, the same file could be cached multiple times

I don't think this is a problem. A namespace is a own bucket/folder with a own strategy and it doesn't know anything regarding to the other namespaces. In my opinion it's ok.

**Comment by eGust** [comment]
implemented in PR #6 
v0.7.0 will be published soon
